# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MicroSpace
email: 1694272297@qq.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "https://microspace.vercel.app" # the subpath of your site, e.g. /blog
url: "https://microspace.vercel.app" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WHU-gentle

# nav settings
nav:
  é¦–é¡µ: '/'
  æ ‡ç­¾: '/tags.html'
  æ—¶é—´çº¿: '/timeline.html'
  å…³äºåšä¸»: '/about.html'
  å‹æƒ…é“¾æ¥: '/friendLink.html'

# åšä¸»
author: true
name: 'æ­¦æ¶µ'
NickName: 'WUH-gentle'
webtitle: 'MicroSpace'
#bio: 'your awesome bio'
about: true
aboutyou: 'æ­¦æ±‰å¤§å­¦è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ä¸“ä¸šå¤§å››åœ¨è¯»æœ¬ç§‘ç”Ÿ'
portraits: '/assets/profile.jpeg' 

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:whugentle@gmail.com'
  weixin: '/assets/wechat.png' # ä½ çš„å¾®ä¿¡äºŒç»´ç å­˜æ”¾çš„åœ°å€
  qq: '/assets/qq.jpg' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='ä½ çš„QQå·'&site=qq&menu=yes
  github: 'https://github.com/WHU-gentle'
  #Codepen: ''
  #weibo: ''
  #instagram: ''
  #Twitter: ''
  #Dribbble: ''
  #Facebook: ''
  #Google: ''
  #zhihu: ''
  #juejin: ''
  #twitch: ''

# åˆ†é¡µ
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# å‹æƒ…é“¾æ¥
friends:
  jekyll: 'https://www.jekyll.com.cn/'
  JerryğŸ€: 'http://60.205.250.231:4000/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitmentè¯„è®º OAuth Application
Gitment: true
Gitment_owner: 'WHU-gentle'  # githubç”¨æˆ·å
Gitment_repo: 'MicroSpace'  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: '631f8e7911669d497388'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: '0dece1f424f7a0bd92e9f405f045b5e52870587e'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: true
baidu-url: '8c788176665ee1f6e84a201ad3932c1f'
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: false
google-ID: ''

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
